"""Cloudflare Tunnel helpers: config rendering and parsing, ``cloudflared`` output parsing, ``.env`` updates.

``deploy/tunnel/setup_tunnel.sh`` drives ``cloudflared``. The fiddly text handling lives here so it
is tested rather than improvised in shell: ``python3 -m agent.tunnel <command>``.

The tunnel only exposes the webhook, health and lead-magnet paths. Every other request (including
the control GUI, which listens on a different port anyway) gets a 404 at Cloudflare's edge and
never reaches the Mac::

    ingress:
      - hostname: hooks.example.com
        path: ^/webhook$
        service: http://127.0.0.1:8443
      - hostname: hooks.example.com
        path: ^/healthz$
        service: http://127.0.0.1:8443
      - service: http_status:404
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable

DEFAULT_TUNNEL_NAME = "automonetize"
# A trailing "/*" exposes everything under that prefix.
EXPOSED_PATHS = ("/webhook", "/healthz", "/lead-magnet/capture", "/lead-magnet/confirm", "/lead-magnet/unsubscribe",
                 "/v1/*", "/openapi.json", "/docs/api", "/docs/api/console.js", "/t/e")
ENV_KEY_URL = "PUBLIC_WEBHOOK_URL"
_LABEL = re.compile(r"^(?!-)[a-z0-9-]{1,63}(?<!-)$")
_UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_ENV_LINE = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$")
_ZERO_TIME = "0001-01-01T00:00:00Z"


class TunnelConfigError(ValueError):
    pass


# ----------------------------------------------------------------------------- hostnames and URLs
def validate_hostname(hostname: str) -> str:
    """A fully qualified DNS name such as ``hooks.example.com``. Returns it normalised (lowercase)."""
    host = (hostname or "").strip().lower().rstrip(".")
    if "://" in host or "/" in host or ":" in host:
        raise TunnelConfigError(f"expected a bare hostname (hooks.example.com), got {hostname!r}")
    labels = host.split(".")
    if len(host) > 253 or len(labels) < 2 or not all(_LABEL.match(label) for label in labels):
        raise TunnelConfigError(f"not a valid fully qualified hostname: {hostname!r}")
    if labels[-1].isdigit():
        raise TunnelConfigError(f"an IP address is not a tunnel hostname: {hostname!r}")
    if host.endswith(".trycloudflare.com"):
        raise TunnelConfigError("trycloudflare.com quick-tunnel URLs change on every restart; use a hostname on your own Cloudflare zone")
    return host


def public_webhook_url(hostname: str, path: str = "/webhook") -> str:
    return f"https://{validate_hostname(hostname)}/{path.lstrip('/')}"


def local_service(host: str = "127.0.0.1", port: int = 8443) -> str:
    return f"http://{host}:{int(port)}"


# ----------------------------------------------------------------------------- cloudflared config
def render_config(tunnel_id: str, credentials_file: str, hostname: str, service: str = "http://127.0.0.1:8443",
                  paths: Iterable[str] = EXPOSED_PATHS) -> str:
    if not re.fullmatch(_UUID, tunnel_id or ""):
        raise TunnelConfigError(f"tunnel id must be a UUID, got {tunnel_id!r}")
    host = validate_hostname(hostname)
    if not re.fullmatch(r"https?://[A-Za-z0-9.\-\[\]:]+", service):
        raise TunnelConfigError(f"unexpected origin service {service!r}")
    lines = [
        "# Generated by deploy/tunnel/setup_tunnel.sh. Re-run the script rather than editing by hand.",
        f"tunnel: {tunnel_id}",
        f"credentials-file: {_yaml_scalar(credentials_file)}",
        "no-autoupdate: true",
        "ingress:",
    ]
    for path in paths:
        clean = "/" + path.lstrip("/")
        rx = f"^{re.escape(clean[:-1])}.*$" if clean.endswith("/*") else f"^{re.escape(clean)}$"
        lines += [f"  - hostname: {host}", f"    path: {rx}", f"    service: {service}"]
    lines.append("  - service: http_status:404")
    return "\n".join(lines) + "\n"


def _yaml_scalar(value: str) -> str:
    return json.dumps(value) if re.search(r"[:#'\"\s{}\[\],&*?|<>=!%@`]", value) else value


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return json.loads(value) if value[0] == '"' else value[1:-1].replace("''", "'")
    return re.sub(r"\s+#.*$", "", value)


def parse_config(text: str) -> dict[str, Any]:
    """Parse the subset of YAML that cloudflared configs use: top-level scalars plus an
    ``ingress`` list of flat mappings. Enough to read back what ``render_config`` writes, or a
    hand-written config of the same shape; anything more nested raises instead of guessing."""
    out: dict[str, Any] = {}
    current_list: list[dict[str, Any]] | None = None
    item: dict[str, Any] | None = None
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.strip()
        if indent == 0:
            key, sep, value = body.partition(":")
            if not sep:
                raise TunnelConfigError(f"line {lineno}: expected 'key: value'")
            key, value = key.strip(), value.strip()
            if value:
                out[key] = _unquote(value)
                current_list = item = None
            else:
                current_list = out.setdefault(key, [])
                item = None
            continue
        if current_list is None:
            raise TunnelConfigError(f"line {lineno}: unexpected indentation")
        if body.startswith("- "):
            item = {}
            current_list.append(item)
            body = body[2:].strip()
        if item is None:
            raise TunnelConfigError(f"line {lineno}: list item expected")
        key, sep, value = body.partition(":")
        if not sep or not value.strip():
            raise TunnelConfigError(f"line {lineno}: nested blocks are not supported")
        item[key.strip()] = _unquote(value)
    return out


def summarize_config(cfg: dict[str, Any]) -> dict[str, Any]:
    """Tunnel id, hostnames, exposed paths, and whether a catch-all 404 closes the ingress."""
    rules = cfg.get("ingress") or []
    if not rules:
        raise TunnelConfigError("config has no ingress rules")
    last = rules[-1]
    catch_all = "hostname" not in last and "path" not in last
    return {
        "tunnel": cfg.get("tunnel", ""),
        "credentials_file": cfg.get("credentials-file", ""),
        "hostnames": sorted({r["hostname"] for r in rules if "hostname" in r}),
        "paths": [r.get("path", "") for r in rules[:-1]],
        "services": sorted({r["service"] for r in rules if "service" in r and not r["service"].startswith("http_status:")}),
        "catch_all_404": catch_all and last.get("service", "").startswith("http_status:404"),
    }


# ----------------------------------------------------------------------------- cloudflared output
def parse_create_output(text: str) -> tuple[str, str]:
    """``cloudflared tunnel create NAME`` → (tunnel id, credentials file path)."""
    tid = re.search(rf"Created tunnel \S+ with id ({_UUID})", text)
    cred = re.search(r"Tunnel credentials written to (.+?\.json)", text)
    if not tid:
        raise TunnelConfigError("could not find the tunnel id in cloudflared's output")
    return tid.group(1), cred.group(1).strip() if cred else ""


def find_tunnel_id(list_json: str, name: str) -> str | None:
    """``cloudflared tunnel list -o json`` → id of the live tunnel called ``name``."""
    try:
        tunnels = json.loads(list_json or "[]") or []
    except json.JSONDecodeError as exc:
        raise TunnelConfigError(f"unreadable tunnel list: {exc}") from None
    for t in tunnels:
        deleted = t.get("deleted_at") or t.get("deletedAt") or ""
        if t.get("name") == name and (not deleted or deleted == _ZERO_TIME):
            return t.get("id")
    return None


def credentials_path(home: str | os.PathLike[str], tunnel_id: str) -> str:
    return str(Path(home) / ".cloudflared" / f"{tunnel_id}.json")


# ----------------------------------------------------------------------------- .env files
def parse_env(text: str) -> dict[str, str]:
    """Parse a shell-style ``.env`` (``KEY=value``, ``export KEY=value``, quotes, comments)."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        m = _ENV_LINE.match(raw)
        if not m or raw.lstrip().startswith("#"):
            continue
        key, value = m.group(1), m.group(2).strip()
        if value[:1] in ("'", '"'):
            try:
                parts = shlex.split(value, posix=True)
                value = parts[0] if parts else ""
            except ValueError:
                value = value.strip("'\"")
        else:
            value = re.sub(r"\s+#.*$", "", value)
        out[key] = value
    return out


def read_env_file(path: str | os.PathLike[str]) -> dict[str, str]:
    p = Path(path)
    return parse_env(p.read_text()) if p.exists() else {}


def _shell_value(value: str) -> str:
    return value if re.fullmatch(r"[A-Za-z0-9_./:@%+,=-]*", value) else shlex.quote(value)


def update_env_text(text: str, updates: dict[str, str]) -> str:
    """Replace ``KEY=...`` lines in place (keeping comments and order), append new keys."""
    pending = dict(updates)
    lines = []
    for raw in text.splitlines():
        m = _ENV_LINE.match(raw)
        if m and not raw.lstrip().startswith("#") and m.group(1) in pending:
            key = m.group(1)
            prefix = "export " if raw.lstrip().startswith("export ") else ""
            lines.append(f"{prefix}{key}={_shell_value(pending.pop(key))}")
        else:
            lines.append(raw)
    if pending:
        if lines and lines[-1].strip():
            lines.append("")
        lines += [f"{k}={_shell_value(v)}" for k, v in pending.items()]
    return "\n".join(lines) + "\n"


def update_env_file(path: str | os.PathLike[str], updates: dict[str, str]) -> Path:
    """Atomically rewrite ``path`` with ``updates`` applied; the file is left mode 600 (it holds secrets)."""
    p = Path(path)
    text = p.read_text() if p.exists() else ""
    new = update_env_text(text, updates)
    p.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".env.", dir=p.parent)
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(new)
        os.chmod(tmp, 0o600)
        os.replace(tmp, p)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return p


def write_record(path: str | os.PathLike[str], record: dict[str, Any]) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n")
    return p


# ----------------------------------------------------------------------------- CLI for setup_tunnel.sh
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python3 -m agent.tunnel")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("validate-hostname").add_argument("hostname")
    p = sub.add_parser("render-config")
    p.add_argument("--tunnel-id", required=True)
    p.add_argument("--credentials-file", required=True)
    p.add_argument("--hostname", required=True)
    p.add_argument("--service", default="http://127.0.0.1:8443")
    p.add_argument("--out", required=True)
    sub.add_parser("check-config").add_argument("path")
    sub.add_parser("parse-create")  # stdin
    sub.add_parser("find-id").add_argument("name")  # stdin: tunnel list JSON
    p = sub.add_parser("write-env")
    p.add_argument("--env-file", required=True)
    p.add_argument("--hostname", required=True)
    p.add_argument("--path", default="/webhook")
    p.add_argument("--record")
    p.add_argument("--tunnel-id", default="")
    p.add_argument("--tunnel-name", default=DEFAULT_TUNNEL_NAME)
    p.add_argument("--config-file", default="")
    args = ap.parse_args(argv)
    try:
        if args.cmd == "validate-hostname":
            print(validate_hostname(args.hostname))
        elif args.cmd == "render-config":
            text = render_config(args.tunnel_id, args.credentials_file, args.hostname, args.service)
            Path(args.out).parent.mkdir(parents=True, exist_ok=True)
            Path(args.out).write_text(text)
            print(args.out)
        elif args.cmd == "check-config":
            summary = summarize_config(parse_config(Path(args.path).read_text()))
            print(json.dumps(summary))
            if not summary["catch_all_404"]:
                print("ingress must end with a catch-all 'service: http_status:404'", file=sys.stderr)
                return 1
        elif args.cmd == "parse-create":
            tid, cred = parse_create_output(sys.stdin.read())
            print(tid)
            if cred:
                print(cred)
        elif args.cmd == "find-id":
            tid = find_tunnel_id(sys.stdin.read(), args.name)
            if not tid:
                return 1
            print(tid)
        elif args.cmd == "write-env":
            url = public_webhook_url(args.hostname, args.path)
            update_env_file(args.env_file, {ENV_KEY_URL: url})
            if args.record:
                write_record(args.record, {"hostname": validate_hostname(args.hostname), "public_webhook_url": url,
                                           "tunnel_id": args.tunnel_id, "tunnel_name": args.tunnel_name,
                                           "config_file": args.config_file})
            print(url)
    except TunnelConfigError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
